# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBstopian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bstopianreview_text', models.CharField(max_length=200, null=True)),
                ('listb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.List')),
            ],
        ),
        migrations.RenameField(
            model_name='listreviews',
            old_name='list',
            new_name='listr',
        ),
    ]
