# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0003_subcategory_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='imageList',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
