# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0004_list_imagelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BstopianReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bstopianreview_text', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_ratings', models.IntegerField(null=True)),
                ('restaurant_rankings', models.IntegerField(null=True)),
                ('restaurant_total', models.IntegerField(null=True)),
                ('restaurant_imageList', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_ratings', models.IntegerField(null=True)),
                ('restaurant_rankings', models.IntegerField(null=True)),
                ('restaurant_total', models.IntegerField(null=True)),
                ('restaurant_imageList', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_text', models.CharField(max_length=200, null=True)),
                ('reviewU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file1.Restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='listbstopian',
            name='listb',
        ),
        migrations.RemoveField(
            model_name='listreviews',
            name='listr',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='ListBstopian',
        ),
        migrations.DeleteModel(
            name='ListReviews',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.RestaurantList'),
        ),
        migrations.AddField(
            model_name='bstopianreviews',
            name='reviewB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file1.Restaurant'),
        ),
    ]
