# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0005_auto_20160625_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlist',
            name='restaurant_imageList',
        ),
        migrations.RemoveField(
            model_name='restaurantlist',
            name='restaurant_rankings',
        ),
        migrations.RemoveField(
            model_name='restaurantlist',
            name='restaurant_ratings',
        ),
        migrations.RemoveField(
            model_name='restaurantlist',
            name='restaurant_total',
        ),
        migrations.AlterField(
            model_name='restaurantlist',
            name='restaurant_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
