# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0006_auto_20160625_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlist',
            name='restaurant_rankings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurantlist',
            name='restaurant_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurantlist',
            name='restaurant_total',
            field=models.IntegerField(null=True),
        ),
    ]
