# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0007_auto_20160704_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_rankings',
            new_name='restaurant_score',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_total',
        ),
    ]
