# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0008_auto_20160704_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_ratings',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_score',
        ),
    ]
