# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0009_auto_20160704_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bstopianreviews',
            name='reviewB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file1.RestaurantList'),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='reviewU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file1.RestaurantList'),
        ),
    ]
