# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0010_auto_20160704_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_imageList', models.FileField(null=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RenameModel(
            old_name='RestaurantList',
            new_name='CategoryList',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.RenameField(
            model_name='categorylist',
            old_name='restaurant_name',
            new_name='list_name',
        ),
        migrations.RenameField(
            model_name='categorylist',
            old_name='restaurant_rankings',
            new_name='list_rankings',
        ),
        migrations.RenameField(
            model_name='categorylist',
            old_name='restaurant_ratings',
            new_name='list_ratings',
        ),
        migrations.RenameField(
            model_name='categorylist',
            old_name='restaurant_total',
            new_name='list_total',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file1.CategoryList'),
        ),
    ]
