# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0012_shareyourmemory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareYourMemory',
            new_name='ShareYourMemory1',
        ),
    ]
