# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file1', '0014_auto_20160705_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareYourMemory2',
            new_name='ShareYourMemory',
        ),
    ]
